services:
  db:
    image: postgres:16-alpine
    container_name: clinica_vet_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: clinica_vet
      POSTGRES_USER: api_backend
      POSTGRES_PASSWORD: api_backend_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./bd/2-procedures.sql:/docker-entrypoint-initdb.d/02-procedures.sql:ro
      - ./bd/3-triggers.sql:/docker-entrypoint-initdb.d/03-triggers.sql:ro
      - ./bd/4-functions.sql:/docker-entrypoint-initdb.d/04-functions.sql:ro
      - ./bd/5-views.sql:/docker-entrypoint-initdb.d/05-views.sql:ro
      - ./bd/6-roles.sql:/docker-entrypoint-initdb.d/06-roles.sql:ro
      - ./bd/7-rls.sql:/docker-entrypoint-initdb.d/07-rls.sql:ro
      - ./bd/8-hardening.sql:/docker-entrypoint-initdb.d/08-hardening.sql:ro
      - ./bd/9-view-permissions.sql:/docker-entrypoint-initdb.d/09-view-permissions.sql:ro
    networks:
      - vet_net

  cache:
    image: redis:7-alpine
    container_name: clinica_vet_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vet_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: clinica_vet_api
    restart: unless-stopped
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://api_backend:api_backend_pwd@db:5432/clinica_vet
      REDIS_URL: redis://cache:6379
      CACHE_TTL_SECONDS: 600
    depends_on:
      - db
      - cache
    ports:
      - "8080:8080"
    networks:
      - vet_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinica_vet_frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3002:80"
    networks:
      - vet_net

volumes:
  postgres_data:
  redis_data:

networks:
  vet_net:
    driver: bridge
